config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :pets, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pet
  belongs_to :user

  validates :booking_startdate, :booking_enddate, presence: true
  validates :booking_startdate, comparison: { less_than: :booking_enddate, message: "must be before the end date" }
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user

  has_many :bookings

  validates :pet_name, :pet_breed, :pet_type, :pet_region, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :region, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :region])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings
  end

  def create
    # Create a new booking for the current user
    @booking = current_user.bookings.new(booking_params)
    @booking.pet_id = params[:pet_id] # Associate the booking with a specific pet

    if @booking.save
      redirect_to bookings_path, notice: "Booking was successfully created!"
    else
      render :new, alert: "There was an error creating the booking."
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:booking_startdate, :booking_enddate)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    if params[:pet_type].present?
      @pets = Pet.where(pet_type: params[:pet_type])  # Filters by pet_type
    else
      @pets = Pet.all  # else shows ALL pets
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @booking = Booking.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="booking-title-background">
    <div class="booking-title">
      <h1>These are your furry bookings</h1>
    </div>
  </div>

  <div class="booking-main">
    <%# <div class="booking-container"> %>
      <% if @bookings.any? %>
        <% @bookings.each do |booking| %>
          <div class="booking-item">
            <img src="<%= booking.pet.pet_image %>" alt="<%= booking.pet.pet_name %>" class="pet-image" />
            <div class="booking-details">
              <h3><%= booking.pet.pet_name %> </h3>
              <p><strong>From:</strong> <%= booking.booking_startdate %></p>
              <p><strong>To:</strong> <%= booking.booking_enddate %></p>
            <!-- Trigger the pop-up -->
              <button class="view-details-btn" data-bs-toggle="modal" data-bs-target="#petModal<%= booking.id %>">
                View Pet Details
              </button>
            </div>
          </div>

          <!-- Modal for the pet details -->
          <div class="modal fade" id="petModal<%= booking.id %>" tabindex="-1" aria-labelledby="petModalLabel<%= booking.id %>" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="petModalLabel<%= booking.id %>"><%= booking.pet.pet_name %> </h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <img src="<%= booking.pet.pet_image %>" alt="<%= booking.pet.pet_name %>" class="modal-pet-image" />
                  <p><strong>Breed:</strong> <%= booking.pet.pet_breed %></p>
                  <p><strong>Description:</strong> <%= booking.pet.pet_description %></p>
                  <p><strong>Region:</strong> <%= booking.pet.pet_region %></p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="modal-footer-close-button btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>You have no bookings yet.</p>
      <% end %>
    <%# </div> %>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPetmatch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.0)), url('<%= image_path "banner.png" %>')">
  <div>
    <h1>Pet Match</h1>
    <h3>Discover and borrow your favorite pets for unforgettable moments. </h3>
    <%= link_to "Find Your Furry Friend", pets_path, class: "btn btn-success" %>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container">
  <h1 class="text-left mb-4 mt-3">
    <% if params[:pet_type].present? %>
      <%= params[:pet_type] %>s
    <% else %>
      All Pets
    <% end %>
  </h1>

  <div class="mb-4 text-left">
    <%= link_to pets_path do %>
      <%= image_tag 'paw.png', class: 'mx-2', style: 'max-width: 100px;' %>
    <% end %>
    <%= link_to pets_path(pet_type: 'Dog') do %>
      <%= image_tag 'dog.png', class: 'mx-2', style: 'max-width: 100px;' %>
    <% end %>
    <%= link_to pets_path(pet_type: 'Cat') do %>
      <%= image_tag 'cat.png', class: 'mx-2', style: 'max-width: 100px;' %>
    <% end %>
    <%= link_to pets_path(pet_type: 'Bird') do %>
      <%= image_tag 'bird.png', class: 'mx-2', style: 'max-width: 100px;' %>
    <% end %>
  </div>


  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @pets.each do |pet| %>
      <div class="col">
        <div class="card h-100 shadow-lg">
          <%= image_tag pet.pet_image, class: "card-img-top", alt: pet.pet_name %>
          <div class="card-body d-flex flex-column h-100">
            <h5 class="card-title"><%= pet.pet_name %></h5>
            <p class="card-text text-muted">
              A <strong><%= pet.pet_breed %></strong> from <strong><%= pet.pet_region %></strong>
            </p>
            <%= link_to 'Take a look', pet_path(pet), class: 'btn btn-success mt-auto' %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/pets/show.html.erb
<div class="container">
<%# <div class="booking-title-background"> %>

  <h1 class="text-left mb-4 mt-3"></h1>

  <div class="mb-4 text-left">
  <%= link_to pets_path do %>
    <%= image_tag 'paw.png', class: 'mx-2', style: 'max-width: 100px;' %>
  <% end %>
  <%= link_to pets_path(pet_type: 'Dog') do %>
    <%= image_tag 'dog.png', class: 'mx-2', style: 'max-width: 100px;' %>
  <% end %>
  <%= link_to pets_path(pet_type: 'Cat') do %>
    <%= image_tag 'cat.png', class: 'mx-2', style: 'max-width: 100px;' %>
  <% end %>
  <%= link_to pets_path(pet_type: 'Bird') do %>
    <%= image_tag 'bird.png', class: 'mx-2', style: 'max-width: 100px;' %>
  <% end %>
</div>

<div class="row justify-content-center">
  <h1 class="text-center md-8 mb-4" style="margin-top: 2rem;">Meet <%= @pet.pet_name %></h1>

  <div class="card mb-4 shadow-lg rounded-6 border-0" style="max-width: 1000px;">
    <div class="row g-0">
      <div class="col-md-4">
        <%= image_tag @pet.pet_image, class: "img-fluid rounded-start" if @pet.pet_image.present? %>
      </div>
      <div class="col-md-8 rounded-6">
        <div class="card-body ">
          <h2 class="card-title"><%= @pet.pet_name %></h2>
          <ul class="list-unstyled mb-5 rounded-6">
            <li><strong>Type:</strong> <%= @pet.pet_type %></li>
            <li><strong>Breed:</strong> <%= @pet.pet_breed %></li>
            <li><strong>Region:</strong> <%= @pet.pet_region %></li>
            <li class="mt-3 text-muted"><%= @pet.pet_description %></li>
          </ul>
          <!-- Button to trigger modal -->
          <button type="button" class="btn btn-success btn-lg shadow-sm mt-5" data-bs-toggle="modal" data-bs-target="#bookingModal">
            <i class="bi bi-calendar-check"></i> Book Now
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal Structure -->
  <div class="modal fade" id="bookingModal" tabindex="-1" aria-labelledby="bookingModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="bookingModalLabel">Book with <%= @pet.pet_name %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <%= simple_form_for [@pet, @booking], html: { class: "needs-validation" } do |f| %>
          <div class="modal-body">
              <div class="mb-3">
                <%= f.label :booking_startdate, "Start Date", class: "form-label" %>
                <%= f.date_field :booking_startdate, class: "form-control", value: @booking.booking_startdate %>
              </div>
              <div class="mb-3">
                <%= f.label :booking_enddate, "End Date", class: "form-label" %>
                <%= f.date_field :booking_enddate, class: "form-control", value: @booking.booking_enddate %>
              </div>
          </div>
          <div class="modal-footer">
            <%= f.submit "Confirm Booking", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow-lg" style="background-color: #fff2f4">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand ms-4" do %>
      <%= image_tag "logo.png", class: "img-fluid", style: "width: 75px; height: 75px;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%# <%= link_to "Home", root_path, class: "nav-link btn btn-ghost me-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pets", pets_path, class: "nav-link btn btn-ghost me-3" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "avatar.png", class: "avatar me-5", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>